name: textmining
dependencies:
  - python==3.8.13
  - jupyter
  - notebook
  - git
  - numpy
  - jpype1
  - tensorflow
  - pytorch
  - huggingface:transformers
  - pip
  - pip:
    - nltk
    - konlpy
    - matplotlib
    - scikit-learn
    - pyldavis
    - textblob
    - afinn
    - vaderSentiment
    - gensim
    - datasets
    - sentencepiece
    - git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf
